version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "actions/upload-artifact"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    versioning-strategy: widen
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "node-gyp"
    groups:
      dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"