name: Build and Retrieve Compiled Files

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linuxmusl-x64
          - os: ubuntu-22.04
            platform: linux-x64
          # - os: macos-12
            # platform: darwin-x64
          - os: windows-latest
            platform: win32-x64
          - os: windows-latest
            platform: win32-ia32

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --omit=optional

    - name: Create a folder for the tarball
      run: |
        mkdir release
        cd release
        mkdir lib

    - name: Build and run Docker container
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'windows')
      run: |
        # Build image
        docker build --build-arg PLATFORM=${{ matrix.PLATFORM }} -t ${{ matrix.PLATFORM }} . -f ./.github/Dockerfile

        # Run container and copy the built file
        docker run --name ${{ matrix.PLATFORM }} ${{ matrix.PLATFORM }}

        # Copy .node file from the container        
        docker cp ${{ matrix.PLATFORM }}:/heif-converter/src/build/Release/converter.node ./release/lib/converter.${{ matrix.PLATFORM }}.node
    
    - name: Copy .dll files from the container (Windows)
      if: contains(matrix.os, 'windows')
      env:
        SRC_PATH: /heif-converter/src/build/Release
      run: |
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/heif.dll ./release/lib/heif.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/turbojpeg.dll ./release/lib/turbojpeg.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/jpeg62.dll ./release/lib/jpeg62.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/libde265.dll ./release/lib/libde265.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/libx265.dll ./release/lib/libx265.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/libpng16.dll ./release/lib/libpng16.dll
        docker cp ${{ matrix.PLATFORM }}:${{ env.SRC_PATH }}/zlib1.dll ./release/lib/zlib1.dll

    - name: Clean up the Docker container (Windows and Linux)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'windows')
      run: docker container rm ${{ matrix.PLATFORM }}

    - name: Configure and Build on OSX
      if: contains(matrix.os, 'mac')
      run: |
        # Install nasm (useful for vcpkg)
        brew install nasm

        # Install python setup tools
        pip3 install setuptools

        # Clone vcpkg and install libheif
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install libheif

        # Build project
        npm run configure
        npm run build

        # Run tests
        # npm run test

        # Copy .node in the release folder
        cp ./src/build/Release/converter.node ./release/lib/converter.${{ matrix.PLATFORM }}.node

    - name: Create tarball of the release folder
      run: |
        cd ./release
        tar -czf ${{ matrix.platform }}.tar.gz *

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./release/${{ matrix.platform }}.tar.gz
