name: Platform tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'package.json'
      - 'platform-tests.yml'
      - '**/npm/**/Dockerfile'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linuxmusl-x64
          - os: ubuntu-22.04
            platform: linux-x64
          - os: macos-12
            platform: darwin-x64
          - os: windows-latest
            platform: win32-x64
          - os: windows-latest
            platform: win32-ia32

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: '18'

    - name: use Docker image to test package (Linux)
      if: contains(matrix.os, 'ubuntu')
      run: docker build -t ${{ matrix.PLATFORM }} . -f ./npm/${{ matrix.PLATFORM }}/Dockerfile

    - name: Install dependencies and test package (Win32 & OSX)
      if: "!contains(matrix.os, 'ubuntu')"
      run: |
        npm install
        npm run test